version: "3.8"

services:
  express:
    container_name: slidedrip_express
    build: 
      context: ./backend/express-backend
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    volumes:
      - ./backend/express-backend:/app
    depends_on:
      - fastapi
      - redis
    networks:
      - slidedrip_network

  fastapi:
    container_name: slidedrip_fastapi
    build: 
      context: ./backend/fastapi-text-service
    ports:
      - "8000:8000"
    volumes:
      - ./backend/fastapi-text-service:/app
    networks:
      - slidedrip_network

  redis:           
    image: "redis:alpine"
    container_name: slidedrip_redis
    ports:
      - "6379:6379"
    networks:
      - slidedrip_network

networks:
  slidedrip_network:
    driver: bridge

volumes:          
  redis_data:     
    driver: local