version: "3.8"

services:
  express:
    container_name: slidedrip_express
    build: ./backend/express-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/express-backend/.env
    volumes:
      - ./backend/express-backend:/app
      - /app/node_modules
    depends_on:
      - fastapi
      - redis   # Add dependency on Redis
    dns:
      - 8.8.8.8
      - 8.8.4.4

  fastapi:
    container_name: slidedrip_fastapi
    build: ./backend/fastapi-text-service
    ports:
      - "8000:8000"
    volumes:
      - ./backend/fastapi-text-service:/app
      - /app/__pycache__

  redis:           
    image: "redis:alpine"
    container_name: slidedrip_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:          
  redis_data:     
    driver: local